import Head from "next/head";
import Hero from "@/components/Hero";
import Genre from "@/components/Genre";
import SectionListFilm from "@/components/SectionListFilm";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <div className="scroll-smooth">
      <Head>
        <title>Nonton Kuy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-small.png" />
      </Head>
      <main className="bg-gray-900 h-full">
        <Hero />
        <Genre />
        <SectionListFilm />
        <Footer />
      </main>
    </div>
  );
}
